[build]
publish = "public"
command = "hugo --gc --minify"
[build.environment]
HUGO_VERSION = "0.89.4"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "17.1.0"
# NPM_VERSION is not configured as it defaults to the version included with node
HUGO_ENV = "production"
NPM_FLAGS = "--production"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[dev]
  framework = "#custom"
  command = "npx rimraf public resources functions && hugo server --bind=0.0.0.0 --disableFastRender"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false
